// In this file you can specify the trial data for your experiment
const trial_info = {
    key_press_practice: [
      {
          question: "Are the two objects the same?",
          picture: 'images/1_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '1',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/1_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '1',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/1_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '1',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/1_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '1',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/2_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '2',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/2_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '2',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/2_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '2',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/2_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '2',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/3_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '3',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/3_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '3',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/3_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '3',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/3_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '3',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
    ],
    key_press_main: [
      {
          question: "Are the two objects the same?",
          picture: 'images/4_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '4',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/1_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '4',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/4_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '4',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/4_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '4',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/5_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '5',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/5_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '5',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/5_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '5',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/5_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '5',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/6_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '6',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/6_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '6',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/6_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '6',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/6_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '6',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/7_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '7',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/7_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '7',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/7_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '7',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/7_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '7',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/8_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '8',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/8_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '8',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/8_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '8',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/8_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '8',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/9_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '9',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/9_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '9',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/9_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '9',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/9_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '9',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/10_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '10',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/10_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '10',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/10_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '10',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/10_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '10',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/11_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '11',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/11_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '11',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/11_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '11',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/11_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '11',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/12_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '12',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/12_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '12',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/12_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '12',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/12_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '12',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/13_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '13',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/13_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '13',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/13_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '13',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/13_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '13',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/14_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '14',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/14_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '14',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/14_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '14',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/14_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '14',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/15_50_same.jpg',
          degree_of_rotation: '50',
          picture_number: '15',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/15_150_same.jpg',
          degree_of_rotation: '150',
          picture_number: '15',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'same'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/15_50_different.jpg',
          degree_of_rotation: '50',
          picture_number: '15',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
      {
          question: "Are the two objects the same?",
          picture: 'images/15_150_different.jpg',
          degree_of_rotation: '150',
          picture_number: '15',
          key1: 'f',
          key2: 'j',
          f:'same',
          j:'different',
          expected: 'different'
      },
  ]
};
